### ISSUE TITLE
Project Page Stable Baselines3

### ISSUE THREAD

**Issue by araffin** [yuanmingqi/rl-exploration-baselines#2]
Hello,

nice project =)

We would be interested if you could do a pull request on [stable-baselines3](https://github.com/DLR-RM/stable-baselines3) where you add your project to the [documentation](https://stable-baselines3.readthedocs.io/en/master/misc/projects.html) (project section) ;)

**Comment by yuanmingqi** [comment]
Wow! Thanks for your recognition. That's my great pleasure!

**Comment by araffin** [comment]
Merci =)
